apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  namespace: nodejs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/pv0001/