apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: testing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 100Mi