apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-vol
  namespace: jenkins
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/jenkins_vol